# Site settings
title: Charlotte Westerberg
email: cw222kq@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  En sida med skoluppgifter och blogginlägg.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
comments: true

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
